model_name: "AMDM"

diffusion:
    sample_mode: "ddpm"
    estimate_mode: "epsilon"
    loss_type: "l1"
    noise_schedule_mode: "cosine"
    T: 18

model_hyperparam:
    layer_num: 12
    time_emb_size: 256 #time embediing
    hidden_size: 1024 
    use_cond: False
    cond_num_cls: 0

optimizer:
    anneal_times: 5
    initial_lr: 0.0001
    final_lr: 0.00001
    teacher_epochs: 400
    ramping_epochs: 200
    student_epochs: 100
    mini_batch_size: 2048
    rollout: 2
    EMA: 
        ema_decay: 0.9999
        ema_start: 5000
        ema_update_rate: 1

data:   
    dataset_name: "STYLE100"
    path: "data/20STYLE"
    dataset_class_name: "STYLE100"
    min_motion_len: 0
    max_motion_len: -1
    data_trim_begin: 0
    data_trim_end: -1
    data_rot_repr: 6d
    data_component: [position, velocity, angle]

    
test:
    test_interval: 10
    test_num_steps: 60
    test_num_trials: 8
    test_num_init_frame: 5
