model_name: "AMDM"

diffusion:
    sample_mode: "ddpm"
    estimate_mode: "epsilon"
    loss_type: "l1"
    noise_schedule_mode: "cosine"
    T: 25 #40 #25
    eval_T: 25 #40 #25
    #denoiser: 

model_hyperparam:
    layer_num: 18
    #cond_mask_prob: 0
    #cond_emb_size: 256 #condition frame for [class, text, etc]
    time_emb_size: 128 #time embediing
    hidden_size: 1024
    use_cond: False
    cond_num_cls: 0
    norm_type: "group_norm"
    act_type: "SiLU"

optimizer:
    consistency_on: False
    consist_loss_weight: 0
    anneal_times: 50
    initial_lr: 0.0005
    final_lr: 0.00001
    initial_teacher_epochs: 2000
    end_teacher_epochs: 300
    teacher_epochs: 85
    ramping_epochs: 0
    student_epochs: 15
    peak_student_rate: 1.0
    mini_batch_size: 2048
    full_T: False
    rollout: 3
    EMA:    
        ema_decay: 0.99
        ema_start: 5000
        ema_update_rate: 1

data:   
    make_npz: False 
    dataset_name: "LAFAN1"
    path: "data/LAFAN1_tpose"
    
    root_rot_offset: -90 #degree
    data_fps: 30
    data_trim_begin: 0
    data_trim_end: -1
    min_motion_len: 0
    max_motion_len: -1
    data_rot_rpr: 6d
    data_component: [position,velocity,angle]

test:
    test_interval: 50
    test_num_steps: 100
    test_num_trials: 4
    test_num_init_frame: 3
