model_name: "AMDM_TEXT"

diffusion:
    sample_mode: "ddpm"
    estimate_mode: "epsilon"
    loss_type: "l1"
    noise_schedule_mode: "cosine"
    T: 20
    eval_T: 20

model_hyperparam:
    layer_num: 18
    #cond_mask_prob: 0
    #cond_emb_size: 256 #condition frame for [class, text, etc]
    time_emb_size: 128 #time embediing
    text_emb_size: 128

    hidden_size: 1024
    use_last_frame_cfg: False
    last_frame_cfg_scale: 0.0
    last_frame_cfg_prob: 0.0

    use_text_cfg: True
    text_cfg_scale: 1.5
    text_cfg_prob: 0.1

    use_cond: False
    cond_num_cls: 0
    norm_type: "group_norm"
    act_type: "SiLU"

optimizer:
    consistency_on: False
    consist_loss_weight: 0
    anneal_times: 50
    initial_lr: 0.0005
    final_lr: 0.0000005
    initial_teacher_epochs: 800
    end_teacher_epochs: 150 
    teacher_epochs: 0
    ramping_epochs: 0
    student_epochs: 10
    peak_student_rate: 1
    mini_batch_size: 4096
    full_T: False
    rollout: 3
    EMA:    
        ema_decay: 0.99
        ema_start: 5000
        ema_update_rate: 1


data:   
    load_cache: True 
    dataset_name: "HumanML3D"
    dataset_class_name: "HumanML3D_TEXT"
    path: "./data/HumanML3D/new_joint_vecs"
    text_path: "./data/HumanML3D/texts"
    train_split: "./data/HumanML3D/train.txt"
    val_split: "./data/HumanML3D/val.txt"
    test_split: "./data/HumanML3D/test.txt"
    text_model_path: "lm/t5-small" #"./lm/clip-vit-large-patch14" #"./lm/GIST-all-MiniLM-L6-v2"
    lm_framework: "transformers_encdec"

    data_fps: 30
    root_rot_offset: 180
    min_motion_len: 0
    max_motion_len: -1
    data_trim_begin: 0
    data_trim_end: -1
    data_rot_repr: 6d
    data_component: [position]

    
test:
    test_interval: 50
    test_num_steps: 200
    test_num_trials: 5
    test_num_init_frame: 4
