env_module: "policy.envs.inpaint_env:InpaintEnv"
env_name: "InpaintEnv"
num_parallel: 6
num_parallel_test: 1
max_timestep: 690
frame_skip: 1

model_type: 'inpaint'

edit:
  repaint_step: 1
  interact_stop_step: -1 

  #full:
   
  #  0:
  #    interact_stop_step: 4 #-1
  #    start_frame: 200 #120 #210 #300
  #    end_frame: 231 #171 #360 #510 #600
  #    val: data/LAFAN1_tpose/dance2_subject2.bvh
  #    data_start_frame: 1 #301
  #    data_end_frame: 32 #541 #601

    
  #  1:
  #    interact_stop_step: 4
  #    start_frame: 381 #120 #210 #300
  #    end_frame: 412 #171 #360 #510 #600
  #    val: data/LAFAN1_tpose/dance2_subject2.bvh
  #    data_start_frame: 1 #301
  #    data_end_frame: 32 #541 #601
  
  #full_trajectory:
  #   start_frame: 0 #210 #300
  #   end_frame: 5000 #510 #600
  #   val: 'circle' #data/100STYLE/Chicken/Chicken_TR1.bvh
  #   data_start_frame: 0 #241 #301
  #   data_end_frame: 5000 #741 #601

  full_rotation:  #deep fk
    start_frame: 100 #210 #300
    end_frame: 101 #510 #600
    val: data/LAFAN1_tpose/dance2_subject3.bvh # miscs/interact_temp/positions.npy
    data_start_frame: 1701 #301
    data_end_frame: 1702 #601
  
  #full_joint: #deep ik
  #  start_frame: 1 #210 #300
  ##  end_frame: 601 #510 #600
  #  val:  data/LAFAN1_tpose/run1_subject5.bvh
  #  data_start_frame: 1 #301
  #  data_end_frame: 601 #601

  #heading:
  #  val: 0.01
  #  start_frame: 0
  #  end_frame: -1 
  
  #trajectory:
  #  start_frame: 0
  #  end_frame: -1 
  #  shape: circle #line
  #  radius: 8 # 6-16
  #  direction: side2 # side2 forward backward

  #root_dxdy:
  #  0:
  #    val: 0
  #    start_frame: 0
  #    end_frame: -1 
  #  1:
  #    val: 0
  #    start_frame: 0
  #    end_frame: -1 
  
  #position:
  #  Head:
  #    1:
  #      val: 0.4 #y axis is the up axis   
  #      start_frame: 5
  #      end_frame: 1000

    #Hips:
    #  1: 
    #    val: 0.4
    #    start_frame: 30
    #    end_frame: 1000

  #angle:
  #velocity:
