env_module: "policy.envs.joystick_env:JoystickEnv"
env_name: "JoystickEnv"
num_parallel: 512
num_parallel_test: 1

max_timestep: 400
max_timestep_test: 1000
frame_skip: 1

#text: ['sidestep', 'forward', 'backward', 'stand still',',']


#AMDM
action_scale: 1.0
random_scale: 1.0

test_action_scale: 2.0
test_random_scale: 0.0
clip_scale: 5

model_type: 'amdm'
action_mode: 'full' #epsilon, locomotion
action_rgr_step: [4,3,2]
action_step: [14,13,12,11,10,9,8,7,6,5,4,3,2]



#HUMOR
#action_scale: 1
#model_type: 'humor'

#mvae
#action_scale: 1
#model_type: 'mvae'
