env_module: "policy.envs.path_env:PathEnv"
env_name: "PathEnv"
num_parallel: 512
num_parallel_test: 1

max_timestep: 500
max_timestep_test: 2000
frame_skip: 1

#text: ['sidestep', 'forward', 'backward', 'stand still',',']


#AMDM
action_scale: 1.0
random_scale: 1.0

test_action_scale: 1.0
test_random_scale: 0.0
clip_scale: 3

model_type: 'amdm'
action_mode: 'full' #epsilon, locomotion
action_rgr_step: [5,4]
action_step: [24,22,20,18,16,14,12,10,8,6,5,4]
#HUMOR
#action_scale: 1
#model_type: 'humor'

#mvae
#action_scale: 1
#model_type: 'mvae'
