env_module: "policy.envs.target_env:TargetEnv"
env_name: "TargetEnv"
num_parallel: 512
num_parallel_test: 1

max_timestep: 300
max_timestep_test: 2000
frame_skip: 1

#text: ['sidestep', 'forward', 'backward', 'stand still',',']

#AMDM
action_scale: 1.0 #0.95 during training
random_scale: 0.0

test_action_scale: 1.0
test_random_scale: 0.0

model_type: 'amdm'

action_rgr_step: [4,3]
action_mode: 'full' #epsilon, locomotion
action_step: [39,38,36,34,32,28,25,20,18,15,12,10,8,6,5,4,3]


#HUMOR
#action_scale: 3
#model_type: 'humor'

#mvae
#action_scale: 8
#model_type: 'mvae'