env_module: "policy.envs.target3d_env:TargetEnv3D"
env_name: "TargetEnv3D"
num_parallel: 500
num_parallel_test: 1

max_timestep: 300
max_timestep_test: 2000
frame_skip: 1

#text: ['sidestep', 'forward', 'backward', 'stand still',',']


#AMDM
action_scale: 1
model_type: 'amdm'
init_w_scale: 3
w_penalty_weight: 0.1
action_mode: 'full' #epsilon, locomotion
action_step: [7,6,5,4,3] #[24,23,22,21,20,19,18,17,16,15,14,13,12,11,10,9,8,7,6,5,4,3,2]
repaint: 1

#HUMOR
#action_scale: 3
#model_type: 'humor'

#mvae
#action_scale: 8
#model_type: 'mvae'