env_module: "policy.envs.target_env:TargetEnv"
env_name: "TargetEnv"
num_parallel: 500
num_parallel_test: 1

max_timestep: 300
max_timestep_test: 2000
frame_skip: 1

#text: ['sidestep', 'forward', 'backward', 'stand still',',']

#AMDM
action_scale: 1
model_type: 'amdm'

action_rgr_step: [4,3,2]
action_mode: 'full' #epsilon, locomotion
action_step: [24,23,22,21,20,19,17,15,13,11,9,7,6,4]

random_scale: 1
test_random_scale: 1

#HUMOR
#action_scale: 3
#model_type: 'humor'

#mvae
#action_scale: 8
#model_type: 'mvae'