data:
  dataset_name: "LAFAN1"
  dataset_class_name: "LAFAN1"
  path: "data/LAFAN1"
  min_motion_len: 0
  max_motion_len: -1
  data_trim_begin: 0
  data_trim_end: 0
  data_rot_rpr: 6d
  data_component: [position, velocity, angle, offset]