agent_name: "PPO"
model_name: "PPO"

clip_param: 0.2
ppo_epoch: 20

value_loss_coef: 1.0
entropy_coef:  0.0
use_gae: True
gamma: 0.99
gae_lambda: 0.95  
max_grad_norm: 1.0

lr: 0.0001
final_lr: 0.000001
eps: 0.00000001
lr_decay_type: "exponential"
mini_batch_size: 2000
save_interval: 20

distr_type: fixed #adaptive #adaptive,fixed
distr_std: 0.5